name: dinewith
channels:
#  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip

  - pip:
      - loguru
      - streamlit-aggrid
      - streamlit
      - colormath
      - gcsa
      - pygsheets
