name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: recursive
      - uses: actions/setup-python@v4.1.0
      - uses: pre-commit/action@v3.0.0
